### PR TITLE
Add Adafruit-Blinka to requirements

### PR DESCRIPTION
**Pull request by evaherrada**

### CODE REVIEW

**Comment by sommersoft** [comment]
Does this actually need Blinka? Its just a couple functions returning an array of waveforms...

If Blinka is being added solely because the library is on PyPI, then might as well add it to the `setup.py`: https://github.com/adafruit/Adafruit_CircuitPython_Waveform/blob/master/setup.py#L37

**Comment by evaherrada** [comment]
I’m no really sure. I was just basing this off of it being on the contributing page on the circuitpython website under the list of things that were missing adafruit-blinka as a requirement.

**Comment by makermelissa** [comment]
#6 was a PR for the same thing and it was closed because it was determined that this wasn't needed. Can we put this on an Adabot ignore list so it doesn't show up as something that needs to be done?

**Comment by evaherrada** [comment]
That’d probably be good. I can try to look into that but I’m very unfamiliar with adabot.

**Comment by sommersoft** [comment]
> Can we put this on an Adabot ignore list

Funny thing... I was just working on Adabot and noticed that it was already added to the ignore list. 🌮s all around! 😄

**Comment by makermelissa** [comment]
Is the Adabot ignore list not working then?

**Comment by sommersoft** [comment]
I'll be able to verify in a few; I have it running now. I was running a specific validator which doesn't use the `LIBRAIRES_DONT_NEED_BLINKA` list.

**Comment by evaherrada** [comment]
It is now but it wasn’t when I made the PR a few weeks ago.

**Comment by sommersoft** [comment]
I think it was done during PyCon. I know it was something that came up before (PyCon18, perhaps). but the conversation had a long break...

**Comment by makermelissa** [comment]
Ok, cool.

**Comment by makermelissa** [comment]
I think it was PyCascades that the conversation last came up. Possibly during PyCon18 too, but I wasn’t around then.

**Comment by sommersoft** [comment]
Yeah, PyCascades seems more likely. The Issue was opened in Feb. 😉

**Pull request closed without merging**
